import type { Metadata } from "next";
import {
  Google_Sans_Flex,
  Google_Sans_Code,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const googleSansCode = Google_Sans_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSansFlex.variable} ${googleSansCode.variable} antialiased`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
